### ISSUE TITLE
unable to locate the amount of experience.

### ISSUE THREAD

**Issue by jgriff72** [jechea14/RunescapeArchaeologyArtifactMaterialCalculator#2]
Artifact: Amphora
Amount: 5
['Members']
Traceback (most recent call last):
  File "D:\Python\RSArchArtefactMaterialCalculator-master\ScriptVersion\ArchCalcScript.py", line 164, in <module>
    main()
  File "D:\Python\RSArchArtefactMaterialCalculator-master\ScriptVersion\ArchCalcScript.py", line 21, in main
    experience_info = webscrape_experience(wiki_mat_table)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\RSArchArtefactMaterialCalculator-master\ScriptVersion\ArchCalcScript.py", line 79, in webscrape_experience
    del(experience[1])
        ~~~~~~~~~~^^^
IndexError: list assignment index out of range

**Comment by jechea14** [comment]
I see the issue. I had a function to web scrape the experience part of a table on the Runescape Wiki and it seemed like the table format on the wiki changed recently so the function grabbed the wrong section of the table. I fixed it to grab the correct table section and return the experience like it should. 

Also back then the table in the wiki used to show the price of one material but now it doesn't so I have removed that from my script.

Old output:
```
Artifact: 'prima legio' painting
Amount: 10

Material             Amount  Price     Total Price
-----------------  --------  --------  -------------
White oak               200  1,446 gp  289,200 gp
Samite silk             200  1,567 gp  313,400 gp
Tyrian purple           740  4,217 gp  3,120,580 gp
Zarosian insignia       200  3,429 gp  685,800 gp

Total Cost    XP with outfit          XP without outfit    XP each
------------  ----------------------  -------------------  -----------
4,408,980 gp  459,332.98000000004 xp  433,333.0 xp         43,333.3 xp
``` 

New output:
```
Artifact: amphora
Amount: 5

Material               Amount  Total Price
-------------------  --------  -------------
Everlight silvthril       170  1,631,320 gp
Keramos                   230  860,890 gp

Total Cost    XP with outfit         XP without outfit    XP each
------------  ---------------------  -------------------  -----------
2,492,210 gp  61,833.51000000001 xp  58,333.5 xp          11,666.7 xp
``` 


Thank you for opening an issue!
